const rawData = [
  {
    type: "DevStatus",
    id: "0",
    name: "Discussion",
    description: "Discussion",
    info: "",
    info2: "",
  },
  {
    type: "DevStatus",
    id: "0",
    name: "Hold",
    description: "Hold",
    info: "",
    info2: "",
  },
  {
    type: "DevStatus",
    id: "0",
    name: "Frontend",
    description: "Frontend",
    info: "",
    info2: "",
  },
  {
    type: "DevStatus",
    id: "0",
    name: "BackEnd",
    description: "BackEnd",
    info: "",
    info2: "",
  },
  {
    type: "DevStatus",
    id: "0",
    name: "Feature",
    description: "Feature",
    info: "",
    info2: "",
  },
  {
    type: "DevStatus",
    id: "0",
    name: "Working",
    description: "Working",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "1",
    name: "517",
    description: "Benefits",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "519",
    description: "Benefits/Backend",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "518",
    description: "Benefits/Frontend",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "538",
    description: "Benefits/Projects",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "1",
    name: "514",
    description: "Log System",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "516",
    description: "Log System/Backend",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "515",
    description: "Log System/Frontend",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "539",
    description: "Log System/Projects",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "1",
    name: "526",
    description: "Payroll",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "528",
    description: "Payroll/Backend",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "527",
    description: "Payroll/Frontend",
    info: "",
    info2: "",
  },
  {
    type: "Folder",
    id: "2",
    name: "529",
    description: "Payroll/Projects",
    info: "",
    info2: "",
  },
  {
    type: "Urgency",
    id: "",
    name: "Urgent",
    description: "Urgent",
    info: "",
    info2: "",
  },
  {
    type: "Urgency",
    id: "",
    name: "High",
    description: "High",
    info: "",
    info2: "",
  },
  {
    type: "Urgency",
    id: "",
    name: "Medium",
    description: "Medium",
    info: "",
    info2: "",
  },
  {
    type: "Urgency",
    id: "",
    name: "Low",
    description: "Low",
    info: "",
    info2: "",
  },
];
